// <auto-generated />
using System;
using ECE.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECE.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702101928_Added_ShipmentDomain")]
    partial class Added_ShipmentDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("InventoryItemSerialSequence");

            modelBuilder.Entity("ECE.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ExpiresOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.InventoryItems.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("'INV-' + RIGHT(REPLICATE('0', 10) + CAST(NEXT VALUE FOR InventoryItemSerialSequence AS varchar(10)), 10)");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("SkuId");

                    b.HasIndex("StorageLocationId");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.InventoryItems.InventoryItemTransactions.InventoryItemTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AfterState")
                        .HasColumnType("int");

                    b.Property<int>("BeforeState")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("InventoryItemTransactions", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.InventoryItemsBatches.InventoryItemsBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Lot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ManufacturingDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Lot");

                    b.ToTable("InventoryItemsBatches", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.ProductBrands.ProductBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProductBrands", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.ProductCategories.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DefaultImageRelativePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Products.ProductTags.ProductTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProductTags", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Shipments.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("ExternalLocation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("ScheduledDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Shipments.ShipmentInvntoryItems.ShipmentInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShipmentLineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("ShipmentLineId");

                    b.HasIndex("ShipmentId", "InventoryItemId")
                        .IsUnique();

                    b.ToTable("ShipmentInventoryItems", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Shipments.ShipmentLines.ShipmentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SkuId");

                    b.HasIndex("ShipmentId", "SkuId")
                        .IsUnique();

                    b.ToTable("ShipmentLines", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Shipments.ShipmentTransactions.ShipmentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AfterStatus")
                        .HasColumnType("int");

                    b.Property<int>("BeforeStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentTransactions", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Skus.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DefaultImageRelativePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAvailableForShipment")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("ShelfLifeInDays")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("ProductId", "Code")
                        .IsUnique();

                    b.ToTable("Skus", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Skus.SkuAttributesDefinitions.SkuAttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SkuAttributeDefinitions", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Skus.SkuAttributesValues.SkuAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkuAttributeDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SkuAttributeDefinitionId");

                    b.HasIndex("SkuId", "SkuAttributeDefinitionId")
                        .IsUnique();

                    b.ToTable("SkuAttributeValues", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.StorageLocations.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("Code", "WarehouseId")
                        .IsUnique();

                    b.ToTable("StorageLocations", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Warehouses.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CurrentWarehouseId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("ECE.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductProductTag", b =>
                {
                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductTagsMapping", (string)null);
                });

            modelBuilder.Entity("ECE.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("ECE.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.InventoryItems.InventoryItem", b =>
                {
                    b.HasOne("ECE.Domain.WarehouseDomain.InventoryItemsBatches.InventoryItemsBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECE.Domain.WarehouseDomain.Skus.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECE.Domain.WarehouseDomain.StorageLocations.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Sku");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.InventoryItems.InventoryItemTransactions.InventoryItemTransaction", b =>
                {
                    b.HasOne("ECE.Domain.WarehouseDomain.Warehouses.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECE.Domain.WarehouseDomain.InventoryItems.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.ProductBrands.ProductBrand", b =>
                {
                    b.OwnsOne("ECE.Domain.WarehouseDomain.ProductBrands.ValueObjects.ProductBrandName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProductBrandId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Name");

                            b1.HasKey("ProductBrandId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("ProductBrands");

                            b1.WithOwner()
                                .HasForeignKey("ProductBrandId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.ProductCategories.ProductCategory", b =>
                {
                    b.OwnsOne("ECE.Domain.WarehouseDomain.ProductCategories.ValueObjects.ProductCategoryName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProductCategoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("ProductCategoryId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("ProductCategories");

                            b1.WithOwner()
                                .HasForeignKey("ProductCategoryId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Products.Product", b =>
                {
                    b.HasOne("ECE.Domain.WarehouseDomain.ProductBrands.ProductBrand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ECE.Domain.WarehouseDomain.ProductCategories.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ECE.Domain.WarehouseDomain.Products.ValueObjects.ProductName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Name");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Products.ProductTags.ProductTag", b =>
                {
                    b.OwnsOne("ECE.Domain.WarehouseDomain.Products.ProductTags.ValueObjects.ProductTagName", "TagName", b1 =>
                        {
                            b1.Property<Guid>("ProductTagId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("TagName");

                            b1.HasKey("ProductTagId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("ProductTags");

                            b1.WithOwner()
                                .HasForeignKey("ProductTagId");
                        });

                    b.Navigation("TagName")
                        .IsRequired();
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Shipments.Shipment", b =>
                {
                    b.HasOne("ECE.Domain.WarehouseDomain.Warehouses.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Shipments.ShipmentInvntoryItems.ShipmentInventoryItem", b =>
                {
                    b.HasOne("ECE.Domain.WarehouseDomain.Warehouses.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECE.Domain.WarehouseDomain.InventoryItems.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECE.Domain.WarehouseDomain.Shipments.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECE.Domain.WarehouseDomain.Shipments.ShipmentLines.ShipmentLine", "ShipmentLine")
                        .WithMany()
                        .HasForeignKey("ShipmentLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("InventoryItem");

                    b.Navigation("Shipment");

                    b.Navigation("ShipmentLine");
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Shipments.ShipmentLines.ShipmentLine", b =>
                {
                    b.HasOne("ECE.Domain.WarehouseDomain.Shipments.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECE.Domain.WarehouseDomain.Skus.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shipment");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Shipments.ShipmentTransactions.ShipmentTransaction", b =>
                {
                    b.HasOne("ECE.Domain.WarehouseDomain.Warehouses.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECE.Domain.WarehouseDomain.Shipments.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Skus.Sku", b =>
                {
                    b.HasOne("ECE.Domain.WarehouseDomain.Products.Product", "Product")
                        .WithMany("Skus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ECE.Domain.Common.ValueObjects.Dimensions.Dimensions3D", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("SkuId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("LengthUnit")
                                .HasColumnType("int")
                                .HasColumnName("DimensionLengthUnit");

                            b1.HasKey("SkuId");

                            b1.ToTable("Skus");

                            b1.WithOwner()
                                .HasForeignKey("SkuId");

                            b1.OwnsOne("ECE.Domain.Common.ValueObjects.Dimensions.Dimension", "Height", b2 =>
                                {
                                    b2.Property<Guid>("Dimensions3DSkuId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("DimensionHeight");

                                    b2.HasKey("Dimensions3DSkuId");

                                    b2.ToTable("Skus");

                                    b2.WithOwner()
                                        .HasForeignKey("Dimensions3DSkuId");
                                });

                            b1.OwnsOne("ECE.Domain.Common.ValueObjects.Dimensions.Dimension", "Length", b2 =>
                                {
                                    b2.Property<Guid>("Dimensions3DSkuId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("DimensionLength");

                                    b2.HasKey("Dimensions3DSkuId");

                                    b2.ToTable("Skus");

                                    b2.WithOwner()
                                        .HasForeignKey("Dimensions3DSkuId");
                                });

                            b1.OwnsOne("ECE.Domain.Common.ValueObjects.Dimensions.Dimension", "Width", b2 =>
                                {
                                    b2.Property<Guid>("Dimensions3DSkuId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("DimensionWidth");

                                    b2.HasKey("Dimensions3DSkuId");

                                    b2.ToTable("Skus");

                                    b2.WithOwner()
                                        .HasForeignKey("Dimensions3DSkuId");
                                });

                            b1.Navigation("Height")
                                .IsRequired();

                            b1.Navigation("Length")
                                .IsRequired();

                            b1.Navigation("Width")
                                .IsRequired();
                        });

                    b.OwnsOne("ECE.Domain.Common.ValueObjects.Prices.Price", "SellingPrice", b1 =>
                        {
                            b1.Property<Guid>("SkuId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SellingPriceAmount");

                            b1.Property<int>("Currency")
                                .HasColumnType("int")
                                .HasColumnName("SellingPriceCurrency");

                            b1.HasKey("SkuId");

                            b1.ToTable("Skus");

                            b1.WithOwner()
                                .HasForeignKey("SkuId");
                        });

                    b.OwnsOne("ECE.Domain.Common.ValueObjects.Weights.Weight", "Weight", b1 =>
                        {
                            b1.Property<Guid>("SkuId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Unit")
                                .HasColumnType("int")
                                .HasColumnName("WeightUnit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("WeightValue");

                            b1.HasKey("SkuId");

                            b1.ToTable("Skus");

                            b1.WithOwner()
                                .HasForeignKey("SkuId");
                        });

                    b.OwnsOne("ECE.Domain.WarehouseDomain.StorageLocations.ValueObjects.StorageRequirements", "StorageRequirements", b1 =>
                        {
                            b1.Property<Guid>("SkuId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Certification")
                                .HasColumnType("int")
                                .HasColumnName("RequiredCertification");

                            b1.Property<int?>("Environment")
                                .HasColumnType("int")
                                .HasColumnName("RequiredEnvironment");

                            b1.Property<int?>("Humidity")
                                .HasColumnType("int")
                                .HasColumnName("RequiredHumidity");

                            b1.Property<int?>("Light")
                                .HasColumnType("int")
                                .HasColumnName("RequiredLight");

                            b1.Property<int?>("Orientation")
                                .HasColumnType("int")
                                .HasColumnName("RequiredOrientation");

                            b1.Property<int?>("Safety")
                                .HasColumnType("int")
                                .HasColumnName("RequiredSafety");

                            b1.Property<int?>("Security")
                                .HasColumnType("int")
                                .HasColumnName("RequiredSecurity");

                            b1.Property<int?>("StorageEquipment")
                                .HasColumnType("int")
                                .HasColumnName("RequiredStorageEquipment");

                            b1.Property<int?>("Temperature")
                                .HasColumnType("int")
                                .HasColumnName("RequiredTemperature");

                            b1.HasKey("SkuId");

                            b1.ToTable("Skus");

                            b1.WithOwner()
                                .HasForeignKey("SkuId");
                        });

                    b.Navigation("Dimensions");

                    b.Navigation("Product");

                    b.Navigation("SellingPrice")
                        .IsRequired();

                    b.Navigation("StorageRequirements");

                    b.Navigation("Weight");
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Skus.SkuAttributesDefinitions.SkuAttributeDefinition", b =>
                {
                    b.OwnsOne("ECE.Domain.WarehouseDomain.Skus.SkuAttributesDefinitions.ValueObjects.SkuAttributeDefinitionName", "Name", b1 =>
                        {
                            b1.Property<Guid>("SkuAttributeDefinitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("SkuAttributeDefinitionId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("SkuAttributeDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("SkuAttributeDefinitionId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Skus.SkuAttributesValues.SkuAttributeValue", b =>
                {
                    b.HasOne("ECE.Domain.WarehouseDomain.Skus.SkuAttributesDefinitions.SkuAttributeDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("SkuAttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECE.Domain.WarehouseDomain.Skus.Sku", "Sku")
                        .WithMany("Attributes")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ECE.Domain.WarehouseDomain.Skus.SkuAttributesValues.ValueObjects.SkuAttributeValueValue", "Value", b1 =>
                        {
                            b1.Property<Guid>("SkuAttributeValueId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Value");

                            b1.HasKey("SkuAttributeValueId");

                            b1.ToTable("SkuAttributeValues");

                            b1.WithOwner()
                                .HasForeignKey("SkuAttributeValueId");
                        });

                    b.Navigation("Definition");

                    b.Navigation("Sku");

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.StorageLocations.StorageLocation", b =>
                {
                    b.HasOne("ECE.Domain.WarehouseDomain.Warehouses.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ECE.Domain.WarehouseDomain.StorageLocations.ValueObjects.StorageRequirements", "StorageRequirements", b1 =>
                        {
                            b1.Property<Guid>("StorageLocationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Certification")
                                .HasColumnType("int")
                                .HasColumnName("CertificationRequirement");

                            b1.Property<int?>("Environment")
                                .HasColumnType("int")
                                .HasColumnName("EnvironmentRequirement");

                            b1.Property<int?>("Humidity")
                                .HasColumnType("int")
                                .HasColumnName("HumidityRequirement");

                            b1.Property<int?>("Light")
                                .HasColumnType("int")
                                .HasColumnName("LightRequirement");

                            b1.Property<int?>("Orientation")
                                .HasColumnType("int")
                                .HasColumnName("OrientationRequirement");

                            b1.Property<int?>("Safety")
                                .HasColumnType("int")
                                .HasColumnName("SafetyRequirement");

                            b1.Property<int?>("Security")
                                .HasColumnType("int")
                                .HasColumnName("SecurityRequirement");

                            b1.Property<int?>("StorageEquipment")
                                .HasColumnType("int")
                                .HasColumnName("StorageEquipmentRequirement");

                            b1.Property<int?>("Temperature")
                                .HasColumnType("int")
                                .HasColumnName("TemperatureRequirement");

                            b1.HasKey("StorageLocationId");

                            b1.ToTable("StorageLocations");

                            b1.WithOwner()
                                .HasForeignKey("StorageLocationId");
                        });

                    b.Navigation("StorageRequirements")
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Warehouses.Employees.Employee", b =>
                {
                    b.HasOne("ECE.Domain.WarehouseDomain.Warehouses.Warehouse", "CurrentWarehouse")
                        .WithMany()
                        .HasForeignKey("CurrentWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentWarehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ECE.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ECE.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECE.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ECE.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductProductTag", b =>
                {
                    b.HasOne("ECE.Domain.WarehouseDomain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECE.Domain.WarehouseDomain.Products.ProductTags.ProductTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.ProductBrands.ProductBrand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.ProductCategories.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Products.Product", b =>
                {
                    b.Navigation("Skus");
                });

            modelBuilder.Entity("ECE.Domain.WarehouseDomain.Skus.Sku", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
